library(biomaRt)

#listEnsembl()
genome = useEnsembl(biomart="ensembl")
listDatasets(genome)
yeastgenome = useEnsembl(biomart="ensembl",dataset="scerevisiae_gene_ensembl")
#listFilters(yeastgenome)
#listAttributes(yeastgenome)
yeastChrI <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="I", mart = yeastgenome)
yeastChrII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="II", mart = yeastgenome)
yeastChrIII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="III", mart = yeastgenome)
yeastChrIV <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="IV", mart = yeastgenome)
yeastChrV <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="V", mart = yeastgenome)
yeastChrVI <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="VI", mart = yeastgenome)
yeastChrVII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="VII", mart = yeastgenome)
yeastChrVIII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="VIII", mart = yeastgenome)
yeastChrIX <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="IX", mart = yeastgenome)
yeastChrX <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="X", mart = yeastgenome)
yeastChrXI <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XI", mart = yeastgenome)
yeastChrXII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XII", mart = yeastgenome)
yeastChrXIII <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XIII", mart = yeastgenome)
yeastChrXIV <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XIV", mart = yeastgenome)
yeastChrXV <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XV", mart = yeastgenome)
yeastChrXVI <- getBM(attributes=c('ensembl_gene_id'), filters = 'chromosome_name', values ="XVI", mart = yeastgenome)

SNPs <- getBM(attributes=c('ensembl_gene_id', 'germ_line_variation_source'),filters = 'germ_line_variation_source',values='SGRP', mart = yeastgenome)
yeastORTHhuman <- getBM(attributes=c('ensembl_gene_id'), filters = 'with_hsapiens_homolog',values=TRUE, mart = yeastgenome)
yeastORTHmouse <- getBM(attributes=c('ensembl_gene_id'), filters = 'with_mmusculus_homolog',values=TRUE, mart = yeastgenome)


GO_0006119 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0006119", mart = yeastgenome)
GO_0006406 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0006406", mart = yeastgenome)
GO_0006412 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0006412", mart = yeastgenome)
GO_0006950 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0006950", mart = yeastgenome)
GO_0007049 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0007049", mart = yeastgenome)
GO_0009651 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0009651", mart = yeastgenome)
GO_0016458 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0016458", mart = yeastgenome)
GO_0023052 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0023052", mart = yeastgenome)
GO_0031047 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0031047", mart = yeastgenome)
GO_0031990 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0031990", mart = yeastgenome)
GO_0042254 <- getBM(attributes=c('ensembl_gene_id'), filters = 'go', values ="GO:0042254", mart = yeastgenome)


write.table(yeastChrI, "yeastchrI.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrII, "yeastchrII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrIII, "yeastchrIII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrIV, "yeastchrIV.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrV, "yeastchrV.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrVI, "yeastchrVI.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrVII, "yeastchrVII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrVIII, "yeastchrVIII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrIX, "yeastchrIX.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrX, "yeastchrX.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXI, "yeastchrXI.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXII, "yeastchrXII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXIII, "yeastchrXIII.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXIV, "yeastchrXIV.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXV, "yeastchrXV.txt",row.names=F,quote=F,col.names=F)
write.table(yeastChrXVI, "yeastchrXVI.txt",row.names=F,quote=F,col.names=F)


write.table(yeastORTHhuman, "yeastorthuman.txt",row.names=F,quote=F,col.names=F)
write.table(yeastORTHmouse, "yeastortmouse.txt",row.names=F,quote=F,col.names=F)




write.table(GO_0006119, "GO_0006119.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0006406, "GO_0006406.txt", row.names=F,quote=F,col.names=F) 
write.table(GO_0006412, "GO_0006412.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0006950, "GO_0006950.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0007049, "GO_0007049.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0009651, "GO_0009651.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0016458, "GO_0016458.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0023052, "GO_0023052.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0031047, "GO_0031047.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0031990, "GO_0031990.txt",row.names=F,quote=F,col.names=F)
write.table(GO_0042254, "GO_0042254.txt",row.names=F,quote=F,col.names=F)

